test:
  stage: test
  script:
    - ln -sf /cache $HOME/.vagrant.d/boxes
    - LANG=en_US.UTF-8 LANGUAGE= LC_CTYPE="en_US.UTF-8" LC_NUMERIC="en_US.UTF-8" LC_TIME="en_US.UTF-8" LC_COLLATE="en_US.UTF-8" LC_MONETARY="en_US.UTF-8" LC_MESSAGES="en_US.UTF-8" LC_PAPER="en_US.UTF-8" LC_NAME="en_US.UTF-8" LC_ADDRESS="en_US.UTF-8" LC_TELEPHONE="en_US.UTF-8" LC_MEASUREMENT="en_US.UTF-8" LC_IDENTIFICATION="en_US.UTF-8" LC_ALL= vagrant up
  # TODO: build ready-to-use vm image as well
  #artifacts:
  #  paths:
  #    - vm.tar.xz

variables:
  GIT_SUBMODULE_STRATEGY: recursive
