#!/bin/bash

set -e

DB="$HOME/.config/dotfiles/db"
HASHDB="$DB/hashes"
mkdir -p "$HASHDB"

echo "Authorize sudo once, to store authorization..."
sudo open
echo "...stored"

contains() {
  match="$1"
  shift
  for e in "$@"; do
    if [ "$e" == "$match" ]; then
      return 0
    fi
  done
  return 1
}

get_var() {
  OUT=$(cat "$script" | grep "# $1: $2" | sed "s|^# $1: ||")
  if [ -z "$OUT" ]; then
    echo "$2"
  else
    echo "$OUT"
  fi
}

_file_hash() {
  FILE="$1"
  FILE_SAFE=$(echo "$FILE" | sed "s|/|@|g")
  FDB="$HASHDB/$FILE_SAFE"
  CURHASH=$(sha256sum "$FILE" | fold -w 64 | head -n 1)
}

store_file_hash() {
  echo "$CURHASH" > "$FDB"
}

has_file_hash() {
  _file_hash "$@"
  if [ ! -e "$FDB" ]; then
    return 1
  fi
}

has_changed_hash() {
  if ! has_file_hash "$@"; then
    echo "ERROR: CANNOT CHECK HASH CHANGE IF HASH NOT IN DB" >&2
    exit 2
  fi
  if [[ "$CURHASH" != "$(cat $FDB)" ]]; then
    return 1
  fi
}

has_changed_hash_multiple() {
  for file in "$@"; do
    has_changed_hash "$file"
  done
}

store_db_val() {
  echo "$2" > "$DB/$1"
}

read_db_val() {
  cat "$DB/$1"
}

compare_db_val() {
  if [[ "$2" != "$(cat "$DB/$!")" ]]; then
    return 1
  fi
}

rem() {
  return 1
}

SCRIPTS=$(find "$(dirname $(dirname $(readlink -f $0)))/.mods.d" -iname "*.sh" | sort)
cd "$HOME"

# TODO: proper argv handling

TARGET="$1"
if [ -z "$TARGET" ]; then
  TARGET="update"
fi

for script in $SCRIPTS; do
  rerun=($(get_var upgrade change)) # rce, but all of this is rce anyways so why bother?
  version=$(get_var rerun)
  files=($(get_var watch-file))

  id="$(basename $(dirname $script))-$(basename $script)"

  export SCRIPTFOLDER="$(dirname $script)"
  export MODFOLDER="$(dirname $SCRIPTFOLDER)"

  if
    ! has_file_hash "$script" || rem if script isnt installed || \
    (has_changed_hash "$FILE" && contains "change" "${rerun[@]}") || rem or if it changed || \
    (has_changed_hash "$FILE" && [ "$TARGET" == "upgrade" ] && contains "upgrade" "${rerun[@]}" && [ -z "$version" ] ) || rem or if target upgrade, and without version || \
    (has_changed_hash "$FILE" && [ "$TARGET" == "upgrade" ] && contains "upgrade" "${rerun[@]}" && ! compare_db_val "$id-version" "$version" ) || rem or if target upgrade, and with different version || \
    (has_changed_hash_multiple "${files[@]}" && contains "watch" "${rerun[@]}") || rem or some files have changed that the script watches || \
  false; then
    echo "Installing/Updating $id..."
    bash -e "$script"
    echo "DONE!"

    for file in "${files[@]}"; do
      store_file_hash "$file"
    done
    store_db_val "$id-version" "$version"
  else
    echo "Skipping $id..."
    # TODO: warning about file-change
  fi
done
