#!/bin/sh
# Copyright (c) 2012 Felipe Contreras
# Modded by Peter Cai for ZeroNet support

# Get ZeroNet dir
ZERONET_HOME=`git config --global --get zeronet.home`
test -z $ZERONET_HOME && echo 'Please set zeronet.home in git global config' && exit 1
ZERONET_KEY=`git config --get zeronet.key`
#test -z $ZERONET_KEY && echo 'Please set zeronet.key in git config' && exit 1

PYTHON='/usr/bin/python2'
test ! -f $PYTHON && PYTHON='/usr/bin/python'

# The first argument can be a url when the fetch/push command was a url
# instead of a configured remote. In this case, use a generic alias.
if test "$1" == "zeronet::$2"; then
	alias=_
else
	alias=$1
fi
url=$2

dir="$GIT_DIR/zeronet/$alias"
prefix="refs/zeronet/$alias"

default_refspec="refs/heads/*:${prefix}/heads/*"

refspec="${GIT_REMOTE_ZERONET_REFSPEC-$default_refspec}"

test -z "$refspec" && prefix="refs"

GIT_DIR="$ZERONET_HOME/data/$url/git"
export GIT_DIR

force=

mkdir -p "$dir"

if test -z "$GIT_REMOTE_ZERONET_NO_MARKS"
then
	gitmarks="$dir/git.marks"
	testgitmarks="$dir/zeronet.marks"
	test -e "$gitmarks" || >"$gitmarks"
	test -e "$testgitmarks" || >"$testgitmarks"
fi

while read line
do
	case $line in
	capabilities)
		echo 'import'
		echo 'export'
		test -n "$refspec" && echo "refspec $refspec"
		if test -n "$gitmarks"
		then
			echo "*import-marks $gitmarks"
			echo "*export-marks $gitmarks"
		fi
		test -n "$GIT_REMOTE_ZERONET_SIGNED_TAGS" && echo "signed-tags"
		test -n "$GIT_REMOTE_ZERONET_NO_PRIVATE_UPDATE" && echo "no-private-update"
		echo 'option'
		echo
		;;
	list)
		git for-each-ref --format='? %(refname)' 'refs/heads/'
		head=$(git symbolic-ref HEAD)
		echo "@$head HEAD"
		echo
		;;
	import*)
		# read all import lines
		while true
		do
			ref="${line#* }"
			refs="$refs $ref"
			read line
			test "${line%% *}" != "import" && break
		done

		if test -n "$gitmarks"
		then
			echo "feature import-marks=$gitmarks"
			echo "feature export-marks=$gitmarks"
		fi

		if test -n "$GIT_REMOTE_ZERONET_FAILURE"
		then
			echo "feature done"
			exit 1
		fi

		echo "feature done"
		git fast-export \
			${testgitmarks:+"--import-marks=$testgitmarks"} \
			${testgitmarks:+"--export-marks=$testgitmarks"} \
			$refs |
		sed -e "s#refs/heads/#${prefix}/heads/#g"
		echo "done"

		;;
	export)
		if test -n "$GIT_REMOTE_ZERONET_FAILURE"
		then
			# consume input so fast-export doesn't get SIGPIPE;
			# git would also notice that case, but we want
			# to make sure we are exercising the later
			# error checks
			while read line; do
				test "done" = "$line" && break
			done
			exit 1
		fi

		before=$(git for-each-ref --format=' %(refname) %(objectname) ')

		git fast-import \
			${force:+--force} \
			${testgitmarks:+"--import-marks=$testgitmarks"} \
			${testgitmarks:+"--export-marks=$testgitmarks"} \
			--quiet

		# figure out which refs were updated
		git for-each-ref --format='%(refname) %(objectname)' |
		while read ref a
		do
			case "$before" in
			*" $ref $a "*)
				continue ;;	# unchanged
			esac
			if test -z "$GIT_REMOTE_ZERONET_PUSH_ERROR"
			then
				echo "ok $ref"
			else
				echo "error $ref $GIT_REMOTE_ZERONET_PUSH_ERROR"
			fi
		done

		echo
		# Sign & publish the ZeroNet site in a subshell
		cd "$ZERONET_HOME" && $PYTHON "zeronet.py" siteSign --publish $url $ZERONET_KEY >& $ZERONET_HOME/log/zero-git-sign.log &
		;;
	option\ *)
		read cmd opt val <<-EOF
		$line
		EOF
		case $opt in
		force)
			test $val = "true" && force="true" || force=
			echo "ok"
			;;
		*)
			echo "unsupported"
			;;
		esac
		;;
	'')
		exit
		;;
	esac
done
